qq/urls.py
from . import views
from django.urls import path


app_name = 'qq'
urlpatterns = [
    path('', views.index, name='index'),
    path('ask/', views.ask_question, name='ask'),
    path('questions/', views.QuestionListView.as_view(), name='questions'),
    path('questions/<int:pk>', views.QuestionDetailView.as_view(),
         name='question-thread'),
    path('questions/<int:pk>/<int:answer_id>/downvote', views.downvote_answer,
         name='downvote-answer'),
    path('questions/<int:pk>/<int:answer_id>/upvote', views.upvote_answer,
         name='upvote-answer'),
    path('questions/<int:pk>/answer', views.answer_question, name='answer'),
]

urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('qq/', include('qq.urls')),
    path('admin/', admin.site.urls),
]

qq/models.py
from django.db import models


class Question(models.Model):
    author = models.CharField(max_length=50)
    question_title = models.CharField(max_length=100)
    question_text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return f'{self.author} - {self.pub_date}'


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    author = models.CharField(max_length=50)
    answer_text = models.TextField()
    votes = models.IntegerField(default=0)
    pub_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return f'{self.author} - {self.pub_date}'

qq/forms.py
from django import forms


class QuestionForm(forms.Form):
    author = forms.CharField(label='Your name', max_length=50)
    question_title = forms.CharField(label='Question title', max_length=100)
    question_text = forms.CharField(label='Your question', widget=forms.Textarea)


class AnswerForm(forms.Form):
    author = forms.CharField(label='Your name', max_length=50)
    answer_text = forms.CharField(label='Your answer', widget=forms.Textarea)

qq/views.py
from . import models
from .forms import AnswerForm, QuestionForm
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.views import generic


def index(request):
    return HttpResponse('placeholder')


def ask_question(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            author = form.cleaned_data['author']
            title = form.cleaned_data['question_title']
            text = form.cleaned_data['question_text']
            models.Question(author=author, question_title=title,
                            question_text=text).save()
            return redirect('qq:questions')
    else:
        form = QuestionForm()
    return render(request, 'qq/ask_question.html', {'form': form})


def answer_question(request, pk):
    question = get_object_or_404(models.Question, pk=pk)
    if request.method == 'POST':
        form = AnswerForm(request.POST)
        if form.is_valid():
            author = form.cleaned_data['author']
            answer = form.cleaned_data['answer_text']
            models.Answer(question=question, author=author,
                          answer_text=answer).save()
            return redirect('qq:question-thread', pk=pk)
    else:
        form = AnswerForm()
    return render(request, 'qq/answer_question.html', {'object': question, 'form': form})


def vote_answer(request, pk, answer_id, amount):
    a = get_object_or_404(models.Answer, pk=answer_id)
    a.votes += amount
    a.save()
    return redirect('qq:question-thread', pk=pk)


def downvote_answer(request, pk, answer_id):
    return vote_answer(request, pk, answer_id, -1)


def upvote_answer(request, pk, answer_id):
    return vote_answer(request, pk, answer_id, 1)


class QuestionListView(generic.ListView):
    model = models.Question


class QuestionDetailView(generic.DetailView):
    model = models.Question

qq/templates/qq/answer_question.html
{% extends "qq/base_generic.html" %}

{% load bootstrap4 %}

{% block content %}
	<a href="{% url 'qq:question-thread' object.id %}">Back to question</a>
	{% include "qq/question_solo.html" %}
	<hr />
	<form action="{% url 'qq:answer' object.id %}" method="post">
		{% csrf_token %}
		{% bootstrap_form form %}
		{% buttons %}
			<button type="submit" class="btn btn-primary">Submit</button>
		{% endbuttons %}
	</form>
{% endblock %}

qq/templates/qq/ask_question.html
{% extends "qq/base_generic.html" %}

{% load bootstrap4 %}

{% block content %}
<form action="{% url 'qq:ask' %}" method="post" class="form">
	{% csrf_token %}
	{% bootstrap_form form %}
	{% buttons %}
		<button type="submit" class="btn btn-primary">Submit</button>
	{% endbuttons %}
</form>
{% endblock %}

qq/templates/qq/base_generic.html
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width,initial-scale=1">
</head>

<body>
	<div class="container">
		{% block content %}<!-- content here -->{% endblock %}
	</div>
	<hr />
	<div class="container text-center">
		<p class="text-muted">Koen Dercksen (TM)</p>
	</div>
</body>
</html>

qq/templates/qq/question_detail.html
{% extends "qq/base_generic.html" %}

{% block content %}
	<a href="{% url 'qq:questions' %}">Back to questions</a>
	<a href="{% url 'qq:answer' object.id %}">Answer question</a>
	<hr />
	{% include "qq/question_solo.html" %}
	<hr />
	{% for answer in object.answer_set.all %}
		<div class="card {% if answer.votes < 0 %}text-white bg-danger{% else %}bg-light{% endif %}">
			<div class="card-header">
				<i>{{ answer.author }} - {{ answer.pub_date }}</i>
			</div>
			<div class="card-body">
				<p class="card-text">{{ answer.answer_text }}</p>
				<footer class="blockquote-footer">
					<p><i>Votes: {{ answer.votes }}</i></p>
					<a href="{% url 'qq:upvote-answer' object.id answer.id %}">Upvote</a>
					<a href="{% url 'qq:downvote-answer' object.id answer.id %}">Downvote</a>
				</footer>
			</div>
		</div>
		<br />
	{% endfor %}
{% endblock %}

qq/templates/qq/question_list.html
{% extends "qq/base_generic.html" %}

{% block content %}
	<a href="{% url 'qq:ask' %}">Ask a question!</a>
	<h2 class="text-center">Question list</h2>

	{% if question_list %}
	<ul class="list-group">
		{% for question in question_list %}
		<li class="list-group-item {% if question.answer_set.all %}list-group-item-success{% endif %}">
			<a href="{% url 'qq:question-thread' question.id %}">
				{{ question.question_title }} - <i>{{ question.author }}</i>
				{% if question.answer_set.all %}<b>[Answered]</b>{% endif %}
			</a>
		</li>
		{% endfor %}
	</ul>
	{% else %}
	<p class="text-muted">No questions available at the moment.</p>
	{% endif %}
{% endblock %}

qq/templates/qq/question_solo.html
<div class="card {% if object.answer_set.all %}bg-success text-white{% else %}bg-light{% endif %}">
	<div class="card-header"><i>{{ object.author }} - {{ object.pub_date }}</i></div>
	<div class="card-body">
		<h5 class="card-title">{{ object.question_title }}</h5>
		<p class="card-text">{{ object.question_text }}</p>
	</div>
</div>